llms:
  - HuggingFaceTB/SmolLM-135M-Instruct
  - HuggingFaceTB/SmolLM-360M-Instruct
  - HuggingFaceTB/SmolLM-1.7B-Instruct
  - Qwen/Qwen3-4B-Instruct-2507
  - google/gemma-3-270m-it
  - google/gemma-3-4b-it
  - google/gemma-3-12b-it
  - google/gemma-3-27b-it
  - meta-llama/Meta-Llama-3-8B-Instruct
  - meta-llama/Llama-3.1-8B-Instruct
  - Qwen/Qwen2.5-7B-Instruct
  - Qwen/Qwen2.5-32B-Instruct
  - mistralai/Mistral-Small-Instruct-2409
  - mistralai/Mistral-Small-24B-Instruct-2501
  - deepseek-ai/DeepSeek-R1-Distill-Qwen-32B
  - microsoft/Phi-3-medium-4k-instruct